// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fruits_app/core/models/product_model.dart';
import 'package:fruits_app/core/models/review_model.dart';
import 'package:fruits_app/features/cart/data/models/cart_item_model.dart';
import 'package:fruits_app/features/cart/data/models/cart_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ReviewModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ReviewModelAdapter());
  }
}
